pipeline {
    agent { 
        label 'nodeg10' 
    }
    tools {
        git 'Default'
    }
    stages {
        stage('Code') {
            steps {
                // Get project code from Github repo
                git url: "https://github.com/raviece2k10/Projects.git", 
                    branch: "main"
                    // credentialsId: 'git-credentials'   // Jenkins credentials ID that stores the GIT authentication details
            }
        }
        stage('Environment') {
            steps {
                // Updating system & installing dependencies
                sh '''
                    sudo apt-get update -y
                    sudo apt-get install docker.io -y
                    sudo apt-get install maven -y
                    docker version; mvn -version; java -version
                    pwd
                '''
            }
        }
        stage('Build') {
            steps {
                // Build the project using maven
                dir('GFG/sandeep-project') {
                    sh 'mvn clean'
                    sh 'mvn package'
                }
            }
        }
        stage('Deploy') {
            steps {
                // Deploy the application in a docker container
                dir('GFG/sandeep-project') {
                    sh 'docker build -t webappimage .'
                    sh 'docker run -dt --name webapp -p 8081:8080 webappimage'
                    sh "docker images; docker ps"
                }
            }
        }
    }
}
